
ROOT = (IDENTIFIER EQUALS CONTEXT)+;
SCOPE = IdOrCallOrScope (DOT IdOrCallOrScope)*;
OPERATOR = IdOrCallOrScope EQUALS CONTEXT;
CONTEXT = OPEN_TABLE OPSORATOMS CLOSE_TABLE | EXPRESSION;
OPSORATOMS = IdOrCallOrScope (OPSORATOMSTAILS)? | ATOM (ATOMORIdOrCallOrScope)*;
OPSORATOMSTAILS = (ATOMORIdOrCallOrScope)+| EQUALS CONTEXT (OPERATOR)*;

IdOrCallOrScope = IDENTIFIER (DOT IdOrCallOrScope)* ()?;

